version: '3.8'

services:
  order-mysql:
    image: mysql:8.0
    container_name: order_db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3308:3306"
    volumes:
      - ./scripts/order_db.sql:/docker-entrypoint-initdb.d/order_db.sql
      - order_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  order_mysql_data:

